%% applyMultiplicationTable.m
% Created by Michael Wild, Version 06.05.2026
% michael.wild@zhaw.ch
%
% Function to obtain irradiation distributions on the panel given the
% multiplication table and radiation distribution.
%
%% Inputs
% 
% MultiplicationTable   :   Multipliers specifying the relation betwee points on the panel and sky elements [-]
% radiationMap          :   Radiation Distribution on Sky Elements [W/m^2/sr]  
% sky_elements          :   Cell Array of Sky Elements generated by hemispherePartition.m
% omega                 :   Near-Ground Surface Broadband Albedo [-]
% omega_fg              :   Far-Ground Surface Broadband Albedo [-]
% configuration         :   Geometric Configuration of the Scene
%
%% Outputs
%
% outData               :   Struct containing: (all values in W/m^2)
%   .globalCheck        :   Sum of Radiation incident on horizontal surface (verification check for GHI) 
%   .avg_irrad_front    :   Average Irradiation on Panel Frontside 
%   .avg_irrad_back     :   Average Irradiation on Panel Backside 
%   .irradFront         :   Total Irradiation Distribution on Panel Frontside 
%   .irradBack          :   Total Irradiation Distribution on Panel Backside
%   .irrad_fract_front_direct : Direct Irradiation Distribution on Panel Frontside
%   .irrad_fract_back_direct : Direct Irradiation Distribution on Panel Backside 
%   .irrad_fract_front_nearground_refl : Near-Ground Reflected Irradiation Distribution on Panel Frontside 
%   .irrad_fract_back_nearground_refl : Near-Ground Reflected Irradiation Distribution on Panel Backside 
%   .irrad_fract_front_farground_refl : Far-Ground Reflected Irradiation Distribution on Panel Frontside 
%
function[outData] = applyMultiplicationTable(MultiplicationTable, radiationMap, sky_elements, omega, omega_fg, configuration)

mu = configuration.mu_deg/180*pi;
gamma = configuration.gamma_deg/180*pi;
alpha_g = configuration.alpha_g_deg/180*pi;
gamma_fg = configuration.gamma_fg_deg/180*pi;
alpha_fg = configuration.alpha_fg_deg/180*pi;

global waitbarhdl;

chi_vec = linspace(-0.5,0.5, size(MultiplicationTable.front_GPF_mult,2));
sig_partition = size(MultiplicationTable.front_GPF_mult,1);

n_pf = [sin(alpha_g)*sin(mu);cos(alpha_g)*sin(mu);cos(mu)];
n_pb = -n_pf;
n_g = [sin(alpha_g)*sin(gamma);cos(alpha_g)*sin(gamma);cos(gamma)];
n_fg = [sin(alpha_fg)*sin(gamma_fg);cos(alpha_fg)*sin(gamma_fg);cos(gamma_fg)];

for i = 1:length(sky_elements)

    loc_elevation = sky_elements{i}.elevation_deg/180*pi;
    loc_azimuth = (mod(sky_elements{i}.azimuth_deg+180,360)-180)/180*pi;
    sigma_s_prime(i) = mod(atan(tan(loc_elevation)/cos(loc_azimuth-alpha_g))+ pi, pi);
    sigma_vec = [sin(loc_azimuth)*cos(loc_elevation);cos(loc_azimuth)*cos(loc_elevation);sin(loc_elevation)];
    n_normal = [0;0;1];

    pf_mult(i) = sky_elements{i}.area*(dot(sigma_vec,n_pf));
    pb_mult(i) = sky_elements{i}.area*(dot(sigma_vec,n_pb));
    g_mult(i) = sky_elements{i}.area*(dot(sigma_vec, n_g));
    fg_mult(i) = sky_elements{i}.area*(dot(sigma_vec, n_fg));
    normal_mult(i) = sky_elements{i}.area*(dot(sigma_vec, n_normal));
end
total_irradiation_front = zeros(1,length(chi_vec));
total_irradiation_back = zeros(1,length(chi_vec));
total_irradiation_global = 0;

irrad_fract_front_direct = zeros(1,length(chi_vec));
irrad_fract_back_direct = zeros(1,length(chi_vec));
irrad_fract_front_nearground_refl = zeros(1,length(chi_vec));
irrad_fract_back_nearground_refl = zeros(1,length(chi_vec));
irrad_fract_front_farground_refl = zeros(1,length(chi_vec));

for i = 1:length(sky_elements) % This has (large!) potential for speed increase through vectorization...

    G_pf = radiationMap(i) * pf_mult(i);
    G_pb = radiationMap(i) * pb_mult(i);
    G_g = radiationMap(i) * g_mult(i);
    G_fg = radiationMap(i) * fg_mult(i);
    G_normal = radiationMap(i) * normal_mult(i);

    idx_low = max(1,floor((sig_partition-1)*sigma_s_prime(i)/pi+1)); % The plus 1 is because array indexing starts at 1. sigh.
    idx_high = idx_low + 1;
    idx_fraction = (((sig_partition-1)*sigma_s_prime(i)/pi+1)-idx_low);

    fractional_irrad_front_direct = G_pf*(idx_fraction*MultiplicationTable.front_GPF_mult(idx_high,:) + (1-idx_fraction)*MultiplicationTable.front_GPF_mult(idx_low,:));
    fractional_irrad_back_direct = G_pb*(idx_fraction*MultiplicationTable.back_GPB_mult(idx_high,:) + (1-idx_fraction)*MultiplicationTable.back_GPB_mult(idx_low,:));
    fractional_irrad_front_nearground_refl = G_g*omega*(idx_fraction*MultiplicationTable.front_GG_mult(idx_high,:) + (1-idx_fraction)*MultiplicationTable.front_GG_mult(idx_low,:));
    fractional_irrad_back_nearground_refl = G_g*omega*(idx_fraction*MultiplicationTable.back_GG_mult(idx_high,:) + (1-idx_fraction)*MultiplicationTable.back_GG_mult(idx_low,:));
    fractional_irrad_front_farground_refl = G_fg*omega_fg*MultiplicationTable.front_GFG_mult;

    irrad_fract_front_direct = irrad_fract_front_direct + fractional_irrad_front_direct;
    irrad_fract_back_direct = irrad_fract_back_direct + fractional_irrad_back_direct;
    irrad_fract_front_nearground_refl = irrad_fract_front_nearground_refl + fractional_irrad_front_nearground_refl;
    irrad_fract_back_nearground_refl = irrad_fract_back_nearground_refl + fractional_irrad_back_nearground_refl;
    irrad_fract_front_farground_refl = irrad_fract_front_farground_refl + fractional_irrad_front_farground_refl;

    total_irradiation_front = total_irradiation_front + fractional_irrad_front_direct + fractional_irrad_front_nearground_refl + fractional_irrad_front_farground_refl;
    total_irradiation_back = total_irradiation_back + fractional_irrad_back_direct + fractional_irrad_back_nearground_refl;
    total_irradiation_global = total_irradiation_global + G_normal;

end
outData.globalCheck = total_irradiation_global;
outData.avg_irrad_front = mean(total_irradiation_front);
outData.avg_irrad_back = mean(total_irradiation_back);
outData.irradFront = total_irradiation_front;
outData.irradBack = total_irradiation_back;
outData.irrad_fract_front_direct = irrad_fract_front_direct;
outData.irrad_fract_back_direct = irrad_fract_back_direct;
outData.irrad_fract_front_nearground_refl = irrad_fract_front_nearground_refl;
outData.irrad_fract_back_nearground_refl = irrad_fract_back_nearground_refl;
outData.irrad_fract_front_farground_refl = irrad_fract_front_farground_refl;
