%% buildMultiplicationTable.m
% Created by Michael Wild, Version 06.05.2026
% michael.wild@zhaw.ch
%
% Handles the geometrical calculations necessary to find the relation
% between hemispherical irradiation intensity and irradiation in panel
% plane.
%
%% Inputs
% 
%   sky_elements    :   Cell Array of Sky Elements generated by hemispherePartition.m
%   mu              :   Module Inclination relative to horizontal [rad]
%   gamma           :   Ground Inclination relative to horizontal [rad]
%   rho_bar         :   Non-dimensional horizontal row spacing [-]
%   h_bar           :   Non-dimensional Module Center height above ground [-]
%   sigma_vec       :   Discrete values for projected sky point elevations [rad]
%   chi_vec         :   Discrete values for panel locations [-]
%   simopts         :   Simulation Options (used here for specification of numerical precision)
%
%% Outputs
%
% outData           :   Struct of Vectors containing the relation between sky elements and locations on the panel.
%
function[outData] = buildMultiplicationTable(mu,rho_bar, gamma, h_bar, chi_vec, sigma_vec, simopts)
global waitbarhdl;
waitbar(0,waitbarhdl, 'Building Multiplication Table');


%% Preallocation of Outputs
loc_irradiation_front_GPF = zeros(length(sigma_vec), length(chi_vec));
loc_irradiation_front_GG = zeros(length(sigma_vec), length(chi_vec));
loc_irradiation_back_GPB = zeros(length(sigma_vec), length(chi_vec));
loc_irradiation_back_GG = zeros(length(sigma_vec), length(chi_vec));

%% Shading Cases
shadingcase(1) = atan((sin(mu)-rho_bar*tan(gamma))/(rho_bar - cos(mu)));
shadingcase(2) = pi - mu;
shadingcase(3) = pi - atan((sin(mu)+rho_bar*tan(gamma))/(rho_bar + cos(mu)));
shadingcase(4) = pi - gamma;


%% Other Setup
max_rows_considered = simopts.maxRowsConsidered;
n_int_d = simopts.n_d;
n_int_zeta = simopts.n_zeta;

d_chi = abs(chi_vec(2) - chi_vec(1));


for i_sigma = 1:length(sigma_vec)
    waitbar(i_sigma/length(sigma_vec), waitbarhdl);
    sigma_s_prime = sigma_vec(i_sigma);
    if (sigma_s_prime < shadingcase(1))
        eta_f = 1 - (rho_bar*(tan(gamma)+tan(sigma_s_prime))/(sin(mu)+tan(sigma_s_prime)*cos(mu)));

        for i_chi = 1:length(chi_vec)
            loc_irradiation_front_GPF(i_sigma,i_chi) = max(0,min(1, (chi_vec(i_chi)+1/2 - eta_f)/d_chi)); % This implementation accomplishes more or less the same, but: at the exact location where the switch direct/no direct shading occurs, the corresponding value is set proportionally. This reduces the necessary discretization dramatically!
            loc_irradiation_front_GG(i_sigma,i_chi) = 0;
            loc_irradiation_back_GPB(i_sigma,i_chi) = 0;
            loc_irradiation_back_GG(i_sigma,i_chi) = 0;
        end

    elseif (sigma_s_prime < shadingcase(2))
        % min max view areas
        for i_chi = 1:length(chi_vec)
            df_min = (h_bar*((2*chi_vec(i_chi)+1)*cos(mu)+2*rho_bar)+2*chi_vec(i_chi)*rho_bar*(sin(mu)-tan(gamma)*cos(mu)))/((2*chi_vec(i_chi)+1)*sin(gamma-mu));
            df_max = -h_bar/(cos(gamma)*(tan(mu)-tan(gamma)));
            db_min = df_max;
            db_max = (h_bar*((2*chi_vec(i_chi)+1)*cos(mu)-2*rho_bar)+2*chi_vec(i_chi)*rho_bar*(tan(gamma)*cos(mu)-sin(mu)))/((2*chi_vec(i_chi)+1)*sin(gamma-mu));

            d_10 = (2*h_bar-sin(mu)-tan(sigma_s_prime)*cos(mu))/(2*cos(gamma)*tan(sigma_s_prime)+2*sin(gamma));
            d_20 = (2*h_bar+sin(mu)+tan(sigma_s_prime)*cos(mu))/(2*cos(gamma)*tan(sigma_s_prime)+2*sin(gamma));

            i_max_f = ceil((df_max-d_20)*cos(gamma)/rho_bar);
            i_min_f = floor((df_min-d_10)*cos(gamma)/rho_bar)+1;
            i_max_b = ceil((db_max-d_20)*cos(gamma)/rho_bar);
            i_min_b = floor((db_min-d_10)*cos(gamma)/rho_bar)+1;

            i_max_f = max(-max_rows_considered, min(max_rows_considered, i_max_f));
            i_min_f = max(-max_rows_considered, min(max_rows_considered, i_min_f));
            i_max_b = max(-max_rows_considered, min(max_rows_considered, i_max_b));
            i_min_b = max(-max_rows_considered, min(max_rows_considered, i_min_b));

            F_front = 0;
            F_back = 0;

            for i_rows = i_min_f:i_max_f
                F_front = F_front - VF_nearground(chi_vec(i_chi), max(d_20+(i_rows-1)*rho_bar/cos(gamma),df_min), min(d_10+i_rows*rho_bar/cos(gamma),df_max), mu, gamma, h_bar,n_int_d,n_int_zeta);
            end
            for i_rows = i_min_b:i_max_b
                F_back = F_back + VF_nearground(chi_vec(i_chi), max(d_20+(i_rows-1)*rho_bar/cos(gamma),db_min), min(d_10+i_rows*rho_bar/cos(gamma),db_max), mu, gamma, h_bar,n_int_d,n_int_zeta);
            end


            loc_irradiation_front_GPF(i_sigma,i_chi) = 1;
            loc_irradiation_front_GG(i_sigma,i_chi) = F_front;
            loc_irradiation_back_GPB(i_sigma,i_chi) = 0;
            loc_irradiation_back_GG(i_sigma,i_chi) = F_back;
        end
    elseif (sigma_s_prime < shadingcase(3))
        for i_chi = 1:length(chi_vec)
            df_min = (h_bar*((2*chi_vec(i_chi)+1)*cos(mu)+2*rho_bar)+2*chi_vec(i_chi)*rho_bar*(sin(mu)-tan(gamma)*cos(mu)))/((2*chi_vec(i_chi)+1)*sin(gamma-mu));
            df_max = -h_bar/(cos(gamma)*(tan(mu)-tan(gamma)));
            db_min = df_max;
            db_max = (h_bar*((2*chi_vec(i_chi)+1)*cos(mu)-2*rho_bar)+2*chi_vec(i_chi)*rho_bar*(tan(gamma)*cos(mu)-sin(mu)))/((2*chi_vec(i_chi)+1)*sin(gamma-mu));

            d_10 = (2*h_bar-sin(mu)-tan(sigma_s_prime)*cos(mu))/(2*cos(gamma)*tan(sigma_s_prime)+2*sin(gamma));
            d_20 = (2*h_bar+sin(mu)+tan(sigma_s_prime)*cos(mu))/(2*cos(gamma)*tan(sigma_s_prime)+2*sin(gamma));

            i_max_f = ceil((df_max-d_10)*cos(gamma)/rho_bar);
            i_min_f = floor((df_min-d_20)*cos(gamma)/rho_bar)+1;
            i_max_b = ceil((db_max-d_10)*cos(gamma)/rho_bar);
            i_min_b = floor((db_min-d_20)*cos(gamma)/rho_bar)+1;

            i_max_f = max(-max_rows_considered, min(max_rows_considered, i_max_f));
            i_min_f = max(-max_rows_considered, min(max_rows_considered, i_min_f));
            i_max_b = max(-max_rows_considered, min(max_rows_considered, i_max_b));
            i_min_b = max(-max_rows_considered, min(max_rows_considered, i_min_b));

            F_front = 0;
            F_back = 0;


            for i_rows = i_min_f:i_max_f
                F_front = F_front - VF_nearground(chi_vec(i_chi), max(d_10+(i_rows-1)*rho_bar/cos(gamma),df_min), min(d_20+i_rows*rho_bar/cos(gamma),df_max), mu, gamma, h_bar,n_int_d,n_int_zeta);
            end
            for i_rows = i_min_b:i_max_b
                F_back = F_back + VF_nearground(chi_vec(i_chi), max(d_10+(i_rows-1)*rho_bar/cos(gamma),db_min), min(d_20+i_rows*rho_bar/cos(gamma),db_max), mu, gamma, h_bar,n_int_d,n_int_zeta);
            end


            loc_irradiation_front_GPF(i_sigma,i_chi) = 0;
            loc_irradiation_front_GG(i_sigma,i_chi)  = F_front;
            loc_irradiation_back_GPB(i_sigma,i_chi) = 1;
            loc_irradiation_back_GG(i_sigma,i_chi) = F_back;
        end
    elseif (sigma_s_prime < shadingcase(4))
        eta_b = 1 + (rho_bar*(tan(gamma)+tan(sigma_s_prime))/(sin(mu)+tan(sigma_s_prime)*cos(mu)));
        for i_chi = 1:length(chi_vec)
            loc_irradiation_front_GPF(i_sigma,i_chi) = 0;
            loc_irradiation_front_GG(i_sigma,i_chi)  = 0;
            loc_irradiation_back_GPB(i_sigma,i_chi) = min(1, max(0, (chi_vec(i_chi)+1/2 - eta_b)/d_chi));
            loc_irradiation_back_GG(i_sigma,i_chi) = 0;
        end
    else
        for i_chi = 1:length(chi_vec)
            loc_irradiation_front_GPF(i_sigma,i_chi) = 0;
            loc_irradiation_front_GG(i_sigma,i_chi)  = 0;
            loc_irradiation_back_GPB(i_sigma,i_chi) = 0;
            loc_irradiation_back_GG(i_sigma,i_chi) = 0;
        end
    end
end

farground_viewfactor = zeros(1, length(chi_vec));

% Far-Front Ground Reflection
for i_chi = 1:length(chi_vec)
    farground_viewfactor(i_chi) = VF_farground(chi_vec(i_chi), mu, gamma, rho_bar, simopts);
end

outData.front_GPF_mult = loc_irradiation_front_GPF;
outData.front_GG_mult = loc_irradiation_front_GG;
outData.back_GPB_mult = loc_irradiation_back_GPB;
outData.back_GG_mult = loc_irradiation_back_GG;
outData.front_GFG_mult = farground_viewfactor;

