%% totalSkyLuminance.m
% Created by Michael Wild, Version 06.05.2026
% michael.wild@zhaw.ch
%
% totalSkyLuminance combines the Perez and Buie models to obtain the
% luminance distribution. It assumes a 6° cutoff for Direct Radiation,
% which corresponds to a common value used for Pyrheliometers.
%
%% Inputs
% 
% sky_elements  :   Cell Array of Sky Elements generated by hemispherePartition.m
% DNI           :   Direct Normal Irradiation [W/m^2]
% GHI           :   Global Horizontal Irradiation [W/m^2]
% sunposition   :   Struct containing .zenith and .azimuth [rad]
% areasinelev   :   Vector of sky element projection areas [m^2] (this is passed separately for speed reasons)
% zenithvec     :   Vector of zenith values of sky_elements [rad] (this is passed separately for speed reasons) 
%
%% Outputs
%
% radiationMap  :   Radiation Distribution on Sky Elements [W/m^2/sr]
%
function[radiationMap] = totalSkyLuminance(sky_elements, DNI, GHI, sunposition, areasinelev, zenithvec)

n_skyelements = length(sky_elements);

Direct_Horizontal = DNI*cos(sunposition.zenith);
DHI = GHI - Direct_Horizontal;
if DHI < 0
    fprintf('Warning: Non-Physical Irradiation Condition detected!\n');
    DHI = 0.05;
end
[lv,gamma] = skyLuminanceBatch(sky_elements, DNI, GHI, DHI, sunposition, zenithvec); % gamma is the angle between positions and sun position. needs to be calculated anyways, but can use it below. accounts for ~40% of computation time...



CSR = 0.3; % This value is an estimate. For non-CSP Applications it should not really matter.
[phi, dirRad] = BuieSolarDistribution(CSR, 100,100);  % numerical values are just precision. 100 should be more than plenty.


% numerically integrate all lv's with respect to horizontal (this corresponds to
% the integral given in eq. 3 of Perez' paper)
total_energy_direct = 0;

for (i = 1:length(sky_elements))
    if (gamma(i) > 6/180*pi) % Outside Circumsolar Region
        rad_direct(i) = 0;
    else % inside the circumsolar region
        lv(i) = 0;
        rad_direct(i) = interp1(phi*1e-3, dirRad, gamma(i));
        total_energy_direct = total_energy_direct + rad_direct(i)*sky_elements{i}.area*cos(gamma(i));
    end

end

total_energy_diffuse = sum(lv.*areasinelev);

LV_scale = DHI/total_energy_diffuse*lv;  % eq. 3.

if (min(LV_scale)>-1e2)
    LV_scale = max(LV_scale,0);
end
rad_direct = DNI/total_energy_direct*rad_direct;

radiationMap = LV_scale + rad_direct;
if any(radiationMap < 0)
    LV_scale;
end

total_energy_global = sum(radiationMap.*areasinelev);
radiationMap = GHI/total_energy_global*radiationMap;